name: ms-thesis
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - matplotlib=3.5.1
  - python=3.10.4
  - tqdm=4.64.0
  - seaborn=0.11.2
  - pandas=1.4.2
  - numpy=1.22.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3
  - opencv=4.5.5
  - ipykernel=6.13.0
