name: ms-thesis
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - matplotlib=3.5.1
  - python=3.10.4
  - tqdm=4.64.0
  - seaborn=0.11.2
  - pandas=1.4.2
  - numpy=1.22.3
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision=0.12.0
  - torchmetrics=0.8.1
  - cudatoolkit=11.3
  - opencv=4.5.5
  - ipykernel=6.13.0
  - albumentations=1.0.3
  - imgaug=0.4.0
  - tensorboard=2.8.0
  - wandb=0.12.14
  - psutil=5.9.0
  - nbstripout=0.5.0
